### PR TITLE
Issue 85: Implement analytical solutions in R

### PR DESCRIPTION
**Pull request by seabbs**
## Description

This PR partially addresses #85 in that it adds analytical solutions in R for the gamma and lognormal with uniform primary censoring.

## Checklist

- [x] My PR is based on a package issue and I have explicitly linked it.
- [x] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [x] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [x] I have tested my changes locally.
- [x] I have added or updated unit tests where necessary.
- [x] I have updated the documentation if required.
- [x] My code follows the established coding standards.
- [x] I have added a news item linked to this PR.
- [x] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Comment by seabbs** [comment]
Numeric is [d-pwindow, d) and analytic is [d, d + pwindow) I think

**Comment by seabbs** [comment]
Currently: 

```r
  pdist_name <- "pgamma"
  pdist <- pgamma
  dprimary_name <- "dunif"
  dprimary <- dunif
  shape <- 2
  rate <- 0.5

  obj <- new_primary_censored_dist(
    pdist,
    dprimary, list(),
    pdist_name, dprimary_name,
    shape = shape, rate = rate
  )

  q_values <- 0:20
  pwindow <- 1

  result <- primary_censored_cdf(obj, q = q_values, pwindow = pwindow, use_numeric = TRUE)
r$> result
 [1] 0.0000000 0.1746233 0.3546345 0.5207711 0.6560827
 [6] 0.7591057 0.8343005 0.8876164 0.9246293 0.9499143
[11] 0.9669703 0.9783585 0.9858984 0.9908554 0.9940947
[16] 0.9962006 0.9975636 0.9984422 0.9990066 0.9993680
[21] 0.9995988

r$> primary_censored_cdf(obj, q = q_values, pwindow = pwindow
    , use_numeric = TRUE)
 [1] 0.0000000 0.0326533 0.1746233 0.3546345 0.5207711
 [6] 0.6560827 0.7591057 0.8343005 0.8876164 0.9246293
[11] 0.9499143 0.9669703 0.9783585 0.9858984 0.9908554
[16] 0.9940947 0.9962006 0.9975636 0.9984422 0.9990066
[21] 0.9993680
```

i.e a right shift

**Comment by seabbs** [comment]
So I think this is the problem and rejigging the indexes seems to have mostly resolved things. I think the remaining issues occur when pwindow crosses 0 which is an awkwardness you need to think about in this approach which we didn't need to before because d is the max not the min for a given window

**Comment by seabbs** [comment]
```r
r$> pdist_name <- "pgamma"
      pdist <- pgamma
      dprimary_name <- "dunif"
      dprimary <- dunif
      shape <- 2
      rate <- 0.5
 
      obj <- new_primary_censored_dist(
        pdist,
        dprimary, list(),
        pdist_name, dprimary_name,
        shape = shape, rate = rate
      )
 
      q_values <- 0:20
      pwindow <- 2
      result_numeric <- primary_censored_cdf(
        obj, q = q_values, pwindow = pwindow, use_numeric = TRUE
      )
      result_analytical <- primary_censored_cdf(
        obj, q = q_values, pwindow = pwindow, use_numeric = FALSE
      )

r$> result_numeric
 [1] 0.00000000 0.01632656 0.10363832 0.26462891 0.43770281
 [6] 0.58842693 0.70759421 0.79670312 0.86095849 0.90612287
[11] 0.93727180 0.95844231 0.97266439 0.98212845 0.98837692
[16] 0.99247507 0.99514769 0.99688212 0.99800288 0.99872438
[21] 0.99918729

r$> result_analytical
 [1] 0.0000000 0.0326533 0.1036383 0.2646289 0.4377028 0.5884269
 [7] 0.7075942 0.7967031 0.8609585 0.9061229 0.9372718 0.9584423
[13] 0.9726644 0.9821284 0.9883769 0.9924751 0.9951477 0.9968821
[19] 0.9980029 0.9987244 0.9991873
```

**Comment by SamuelBrand1** [comment]
> Numeric is [d-pwindow, d) and analytic is [d, d + pwindow)?

It depends where the start is? The analytic approach starts at the end of the primary censor window, e.g. the earliest point an observer can be aware of a primary event.

**Pull request merged**
