### PR TITLE
Issue 76: Add weibull distribution to analytic solutions in vignette

### LINKED ISSUE #76: Add Weibull distribution to analytic solutions in vignette
As per title.

### PR DESCRIPTION
**Pull request by SamuelBrand1**
## Description

This PR adds the Weibull distribution to the analytic solutions currently in "Why it works" vignette, following the same pattern as the Log-Normal and the Gamma.

This PR closes #76 .

## Checklist

- [x] My PR is based on a package issue and I have explicitly linked it.
- [x] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [x] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [x] I have tested my changes locally.
- [x] I have added or updated unit tests where necessary.
- [x] I have updated the documentation if required.
- [x] My code follows the established coding standards.
- [x] I have added a news item linked to this PR.
- [x] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Review by seabbs — COMMENTED** [review]
This looks great. I think we (and I certainly needed this) need some more stepping stones in 3.11. In particular, the target integral in full, why the substitution and then how that allows you to solve.

**Comment by SamuelBrand1** [comment]
I've done a few more steps as well as describing the basic inspiration.

Found a few typos in the intermediate steps as well so good to catch those.

**Comment by seabbs** [comment]
Looks like it needs a spell check

**Review by seabbs — APPROVED** [review]
Really helpful signposting. Looking forward to implementing this.

**Pull request merged**
